version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./images/nginx/conf.d:/etc/nginx/conf.d
  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    #image: php:7.0-fpm
    volumes:
      - ./app:/site
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "shuhui"
      MYSQL_PASSWORD: "123456"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
