version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    restart: always
    volumes:
      - /es/data:/usr/share/elasticsearch/data
      - /es/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:latest 
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: always
    volumes:
      - ./logstash/config:/etc/logstash/conf.d/:ro
      - ./logstash/GeoLiteCity.dat:/etc/logstash/GeoLiteCity.dat:ro
    ports:
      - "5044:5044"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:latest 
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  filebeat:
    image: prima/filebeat
    restart: always
    volumes:
      - ./filebeat/config/filebeat.yml:/filebeat.yml:ro
    volumes_from:
      - nginx
    links:
      - logstash
      - elasticsearch
    depends_on:
      - logstash
      - elasticsearch

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - log:/data/log/nginx/access/:rw
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  log:
    driver: local
